/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SlidesInterface } from "./components/ip-slider-sl-2/interface/slides.interface";
import { SlidesInterface as SlidesInterface1 } from "./components/ip-slider-sl-3/interface/slides.interface";
export namespace Components {
    interface IpSliderSl1 {
        "bulletBtnAria": string;
        "bulletBtnAriaTo": string;
        "isPreviousNextNavigation": boolean;
        "isSlideBullet": boolean;
        "itemToShow": number;
        "nextBtnAria": string;
        "previousBtnAria": string;
        "slideGap": number;
        "slideTitle": string;
    }
    interface IpSliderSl2 {
        "btnNextAria": string;
        "btnPreviousAria": string;
        "slideTitle": string;
        "slideTitleAria": string;
        "slideTitleMobile": string;
        "slides": SlidesInterface[] | string;
    }
    interface IpSliderSl3 {
        "isAutoSlide": boolean;
        "isSlideBullet": boolean;
        "slidePauseIcon": any;
        "slidePlayIcon": any;
        "slides": SlidesInterface1[] | string;
    }
}
declare global {
    interface HTMLIpSliderSl1Element extends Components.IpSliderSl1, HTMLStencilElement {
    }
    var HTMLIpSliderSl1Element: {
        prototype: HTMLIpSliderSl1Element;
        new (): HTMLIpSliderSl1Element;
    };
    interface HTMLIpSliderSl2Element extends Components.IpSliderSl2, HTMLStencilElement {
    }
    var HTMLIpSliderSl2Element: {
        prototype: HTMLIpSliderSl2Element;
        new (): HTMLIpSliderSl2Element;
    };
    interface HTMLIpSliderSl3Element extends Components.IpSliderSl3, HTMLStencilElement {
    }
    var HTMLIpSliderSl3Element: {
        prototype: HTMLIpSliderSl3Element;
        new (): HTMLIpSliderSl3Element;
    };
    interface HTMLElementTagNameMap {
        "ip-slider-sl-1": HTMLIpSliderSl1Element;
        "ip-slider-sl-2": HTMLIpSliderSl2Element;
        "ip-slider-sl-3": HTMLIpSliderSl3Element;
    }
}
declare namespace LocalJSX {
    interface IpSliderSl1 {
        "bulletBtnAria"?: string;
        "bulletBtnAriaTo"?: string;
        "isPreviousNextNavigation"?: boolean;
        "isSlideBullet"?: boolean;
        "itemToShow"?: number;
        "nextBtnAria"?: string;
        "previousBtnAria"?: string;
        "slideGap"?: number;
        "slideTitle"?: string;
    }
    interface IpSliderSl2 {
        "btnNextAria"?: string;
        "btnPreviousAria"?: string;
        "slideTitle"?: string;
        "slideTitleAria"?: string;
        "slideTitleMobile"?: string;
        "slides"?: SlidesInterface[] | string;
    }
    interface IpSliderSl3 {
        "isAutoSlide"?: boolean;
        "isSlideBullet"?: boolean;
        "slidePauseIcon"?: any;
        "slidePlayIcon"?: any;
        "slides"?: SlidesInterface1[] | string;
    }
    interface IntrinsicElements {
        "ip-slider-sl-1": IpSliderSl1;
        "ip-slider-sl-2": IpSliderSl2;
        "ip-slider-sl-3": IpSliderSl3;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-slider-sl-1": LocalJSX.IpSliderSl1 & JSXBase.HTMLAttributes<HTMLIpSliderSl1Element>;
            "ip-slider-sl-2": LocalJSX.IpSliderSl2 & JSXBase.HTMLAttributes<HTMLIpSliderSl2Element>;
            "ip-slider-sl-3": LocalJSX.IpSliderSl3 & JSXBase.HTMLAttributes<HTMLIpSliderSl3Element>;
        }
    }
}
