/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { SlidesInterface } from "./components/ip-slider-sl-1/interface/slides.interface";
export namespace Components {
    interface IpSlider {
    }
    interface IpSliderSl1 {
        "btnNextAria": string;
        "btnPreviousAria": string;
        "slideTitle": string;
        "slideTitleMobile": string;
        "slides": SlidesInterface[] | string;
    }
}
declare global {
    interface HTMLIpSliderElement extends Components.IpSlider, HTMLStencilElement {
    }
    var HTMLIpSliderElement: {
        prototype: HTMLIpSliderElement;
        new (): HTMLIpSliderElement;
    };
    interface HTMLIpSliderSl1Element extends Components.IpSliderSl1, HTMLStencilElement {
    }
    var HTMLIpSliderSl1Element: {
        prototype: HTMLIpSliderSl1Element;
        new (): HTMLIpSliderSl1Element;
    };
    interface HTMLElementTagNameMap {
        "ip-slider": HTMLIpSliderElement;
        "ip-slider-sl-1": HTMLIpSliderSl1Element;
    }
}
declare namespace LocalJSX {
    interface IpSlider {
    }
    interface IpSliderSl1 {
        "btnNextAria"?: string;
        "btnPreviousAria"?: string;
        "slideTitle"?: string;
        "slideTitleMobile"?: string;
        "slides"?: SlidesInterface[] | string;
    }
    interface IntrinsicElements {
        "ip-slider": IpSlider;
        "ip-slider-sl-1": IpSliderSl1;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ip-slider": LocalJSX.IpSlider & JSXBase.HTMLAttributes<HTMLIpSliderElement>;
            "ip-slider-sl-1": LocalJSX.IpSliderSl1 & JSXBase.HTMLAttributes<HTMLIpSliderSl1Element>;
        }
    }
}
